### ISSUE TITLE
WARNING: A terminally deprecated method in java.lang.System has been called

### ISSUE THREAD

**Issue by patpatpat123** [spotbugs/spotbugs-maven-plugin#540] opened 2023-02-12 11:37 UTC
Hello team,

Thank you very much for this plugin.

I am encountering this following issue:

```
[INFO] FindBugs report is already generated C:\Users\me\IdeaProjects\project\target\spotbugsXml.xml. Reusing the report.
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.sonar.plugins.findbugs.FindbugsExecutor (file:/C:/Users/me/.sonar/cache/36f877e376b8a04bb888b19d1c002384/sonar-findbugs-plugin.jar)
WARNING: Please consider reporting this to the maintainers of org.sonar.plugins.findbugs.FindbugsExecutor
WARNING: System::setSecurityManager will be removed in a future release
```

Could you please help?

Thank you

**Comment by hazendaz** [comment] 2023-02-12 18:19
See Readme.  This is just a warning at this time.  This plugin is built on groovy and they have to change to remove the warning.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: patpatpat123 ***@***.***>
Sent: Sunday, February 12, 2023 6:38:02 AM
To: spotbugs/spotbugs-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spotbugs/spotbugs-maven-plugin] WARNING: A terminally deprecated method in java.lang.System has been called (Issue #540)


Hello team,

Thank you very much for this plugin.

I am encountering this following issue:

[INFO] FindBugs report is already generated C:\Users\me\IdeaProjects\project\target\spotbugsXml.xml. Reusing the report.
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.sonar.plugins.findbugs.FindbugsExecutor (file:/C:/Users/me/.sonar/cache/36f877e376b8a04bb888b19d1c002384/sonar-findbugs-plugin.jar)
WARNING: Please consider reporting this to the maintainers of org.sonar.plugins.findbugs.FindbugsExecutor
WARNING: System::setSecurityManager will be removed in a future release


Could you please help?

Thank you

**Comment by hazendaz** [comment] 2023-02-21 01:35
closing as issue is with groovy.  they had a fix then reverted at some point.  we can only wait on them to fix as the issue is theirs.

**Closed by hazendaz** 2023-02-21 01:35 UTC

**Comment by patpatpat123** [comment] 2023-02-21 02:31
Many thanks @hazendaz for the clear explanation
