### ISSUE TITLE
Report generation only works after compiling the sources

### ISSUE THREAD

**Issue by uweplonus** [spotbugs/spotbugs-maven-plugin#93] opened 2018-10-20 10:58 UTC
Today I faced a problem generating my site.
I'm on a project where I do not compile the source files but only execute `mvn site` to generate the site (A Spotbugs Example Project).
Therefore I only run `mvn site` but then the report is not generated.
I had to run at least `mvn compile site` to get the report generated.
This should at least be documented for the plugin that the compiled classes are needed to create the report.

**Comment by hazendaz** [comment] 2018-10-20 16:47
What version are you using?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iloveeclipse** [comment] 2018-10-23 05:45
Spotbugs needs compiled code to run, this is not a bug, it is the way how Spotbugs was designed. So no compile => no results.

**Comment by uweplonus** [comment] 2018-10-23 06:15
As I wrote in the bug report at least a documentation is useful.

**Comment by iloveeclipse** [comment] 2018-10-23 06:19
https://spotbugs.github.io/ says "it can analyze programs compiled for any version of Java, from 1.0 to 1.9."

But if you like to improve the manual, please check https://spotbugs.readthedocs.io/en/latest/introduction.html and try to contribute a fix - click the "Edit on GitHub" link in the upper right corner.

**Comment by hazendaz** [comment] 2018-11-04 04:12
Closing issue here as not an issue with the maven plugin nor design of spotbugs but rather documentation clarity if user so wishes to update that.

**Closed by hazendaz** 2018-11-04 04:12 UTC
Labels: documentation
