### ISSUE TITLE
Maven command (groupId, artifactId, etc.)

### ISSUE THREAD

**Issue by h3xstream** [spotbugs/spotbugs-maven-plugin#2] opened 2017-08-10 18:07 UTC
The README state a command that doesn't work unless special alias are created.
`mvn com.github.spotbugs:spotbugs-maven-plugin:3.1.0-SNAPSHOT:gui`

Based on the maven repository link .. I found this instance of the plugin which work..
`mvn com.github.hazendaz.spotbugs:spotbugs-maven-plugin:3.1.0-RC4:findbugs`

This is much longer than the previous `mvn findbugs:findbugs`

**Comment by hazendaz** [comment] 2017-08-11 01:55
You can run with

```mvn spotbugs:findbugs```

or

```mvn spotbugs:gui```

The readme is identical other than I switched out the details from old plugin to new one.  Its otherwise about as close to the old plugin as possible.  I will cleanup the readme as the longer command is highly unnecessary but I will get that done on the core project first and once merged rebase over here.  I'll also swap out the mojo for spotbugs as soon as I can.  I'll keep this open for time being.

**Comment by h3xstream** [comment] 2017-08-13 02:52
`mvn spotbugs:findbugs` is not possible without additional configuration.

The previous plugin was release with the `org.codehaus.mojo` groupId which is configured by default in Maven.
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.codehaus.mojo%22%20AND%20a%3A%22findbugs-maven-plugin%22

**Comment by hazendaz** [comment] 2017-08-13 22:10
mvn spotbugs:findbugs works for me so I'm not sure I'm fully understanding the issue you are observing here.  What does switch from mojo to another groupId specifically cause, can you show me some more details?  There is barely anything different from the original plugin at this point as original auther has been accepting everyting so at best the only change is to switch to spotbugs:findbugs.  I've confirmed this on multiple projects so I'm not understanding the core problem here.

**Comment by h3xstream** [comment] 2017-08-15 19:43
My suggestion : 
- Either update the groupId to match the README : `mvn com.github.spotbugs:spotbugs-maven-plugin:3.1.0-SNAPSHOT:gui`
- Change the readme to `mvn com.github.hazendaz.spotbugs:spotbugs-maven-plugin:3.1.0-RC4:findbugs`

Bonus: Consider using a groupId that is part default plugin groupId.

**Comment by hazendaz** [comment] 2017-08-15 22:28
Can you show me your error?  I'm not having the issue you are and I think you are mixing issues.  The hazendaz release was prior to this being brought over here.  This copy hasn't been released.  The read me refers to how to run providing full naming.  That is verbatim from original plugin with names changed.  This runs without any of that as I indicated.  Please show me what failure you are getting as I have no real clue what your issue is at the moment.  I'm holding up the release specifically because of this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by h3xstream** [comment] 2017-08-18 15:38
> This copy hasn't been released.

Ah! Now everything is clear. 😄

**Comment by hazendaz** [comment] 2017-09-28 02:01
This is now fixed on this repo and will be released soon.

**Closed by hazendaz** 2017-09-28 02:01 UTC
