### ISSUE TITLE
plugin build setting 

### ISSUE THREAD

**Issue by dylan-tao** [spotbugs/spotbugs-maven-plugin#673] opened 2023-11-22 17:16 UTC
Describe the feature

maven build target file： spotbugs.html，support set htmlOutputDirectory， current: /target/spotbugs.html, but xml can customize the directory settings.

```
<configuration>
  <htmlOutputDirectory>${project.reporting.outputDirectory}</htmlOutputDirectory>
</configuration>
```

**Comment by dylan-tao** [comment] 2023-11-23 16:57
> Describe the feature
> 
> maven build target file： spotbugs.html，support set htmlOutputDirectory， current: /target/spotbugs.html, but xml can customize the directory settings.
> 
> ```
> <configuration>
>   <htmlOutputDirectory>${project.reporting.outputDirectory}</htmlOutputDirectory>
> </configuration>
> ```

How is the progress now？

**Comment by hazendaz** [comment] 2023-11-24 05:17
Hi @dylan-tao. What is the need to do that?  Can you explain what you are after here?  Maybe contribute a PR once its understood if its necessary or not.

**Comment by dylan-tao** [comment] 2023-11-25 15:08
To make it clearer for team members to view bug lists and statistics in HTML instead of XML. For example: PMD plug-ins can be customized, the report generated to the same directory, you can better manage code quality.

**Comment by dylan-tao** [comment] 2023-11-25 15:08
> To make it clearer for team members to view bug lists and statistics in HTML instead of XML. For example: PMD plug-ins can be customized, the report generated to the same directory, you can better manage code quality.

To make it clearer for team members to view bug lists and statistics in HTML instead of XML. For example: PMD plug-ins can be customized, the report generated to the same directory, you can better manage code quality.

**Comment by dylan-tao** [comment] 2023-11-25 15:24
> Hi @dylan-tao. What is the need to do that? Can you explain what you are after here? Maybe contribute a PR once its understood if its necessary or not.

see： https://github.com/mathieucarbou/license-maven-plugin/issues/673

**Comment by hazendaz** [comment] 2023-12-03 00:03
@dylan-tao Can you offer up a pull request on this feature?  I'm limited in time and it would be easier if you do that to get support out.

**Comment by hazendaz** [comment] 2023-12-17 05:08
closing as this is already present in support.  

See
```
    /**
     * Location where generated html will be created.
     *
     */
    @Parameter(defaultValue = '${project.reporting.outputDirectory}', required = true)
    File outputDirectory
```

**Closed by hazendaz** 2023-12-17 05:08 UTC

**Comment by dylan-tao** [comment] 2023-12-20 15:57
> closing as this is already present in support.
> 
> See
> 
> ```
>     /**
>      * Location where generated html will be created.
>      *
>      */
>     @Parameter(defaultValue = '${project.reporting.outputDirectory}', required = true)
>     File outputDirectory
> ```

When I set outputDirectory to generate html report will report an error. Theoretically, xml generation should be necessary, and it needs to be translated from xml to html. The following error will be reported:, 
```
[INFO] --- spotbugs-maven-plugin:4.8.2.0:spotbugs (spotbugs) @ beeico-base ---
[INFO] Fork Value is true
     [java] The following errors occurred during analysis:
     [java]   Could not generate HTML output
     [java]     java.lang.RuntimeException: Error while disabling XML external entities
     [java]       At edu.umd.cs.findbugs.xml.XMLUtil.buildTransformerFactory(XMLUtil.java:60)
     [java]       At edu.umd.cs.findbugs.HTMLBugReporter.finish(HTMLBugReporter.java:69)
     [java]       At edu.umd.cs.findbugs.BugReportDispatcher.lambda$forEach$13(BugReportDispatcher.java:124)
```
It is recommended to refer to PMD's settings to unify directory management: target Directory (xml generation directory) and rulesetsTargetDirectory (configuration rule file storage directory), and then html is generated under ${project.reporting.outputDirectory} by default

**Comment by hazendaz** [comment] 2024-02-11 01:02
Just quick circle back on this, your issue is likely a library mismatch and presumably you are using > java 9.  The issue is not with the directory, its failing to prevent XXE due to missing library.  That tends to lean on library mismatch since java 8.  The actual code you are looking at is here https://github.com/spotbugs/spotbugs/blob/6fe5ba97f8769af2b264920fe07d8d3cace9242b/spotbugs/src/main/java/edu/umd/cs/findbugs/xml/XMLUtil.java#L53.

I don't understand your comments on PMD. That is an entirely different plugin.

**Comment by dylan-tao** [comment] 2024-07-31 12:07
> closing as this is already present in support.
> 
> See
> 
> ```
>     /**
>      * Location where generated html will be created.
>      *
>      */
>     @Parameter(defaultValue = '${project.reporting.outputDirectory}', required = true)
>     File outputDirectory
> ```

please

> closing as this is already present in support.
> 
> See
> 
> ```
>     /**
>      * Location where generated html will be created.
>      *
>      */
>     @Parameter(defaultValue = '${project.reporting.outputDirectory}', required = true)
>     File outputDirectory
> ```
@hazendaz 
version: 4.8.6.2
Please test, the configuration item has been invalid, the default generated report is wrong under target, it should be in the site directory, and the above ${project.reporting.outputDirectory} is invalid.
